// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCScYrrhIdu2-dssoZXYRL3mxek3tDf-Wc',
    appId: '1:898837897298:web:e9f0b1fb3397a0549b7f8b',
    messagingSenderId: '898837897298',
    projectId: 'crud-e044a',
    authDomain: 'crud-e044a.firebaseapp.com',
    storageBucket: 'crud-e044a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbKDpKSPsouMJiMAn1tiJayu_xJkdzZvs',
    appId: '1:898837897298:android:70b7eee0c1c1a2db9b7f8b',
    messagingSenderId: '898837897298',
    projectId: 'crud-e044a',
    storageBucket: 'crud-e044a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9LV99QjdzNh5A2X_ZIHHrbhgJ-4fsnME',
    appId: '1:898837897298:ios:5e13356d86c169119b7f8b',
    messagingSenderId: '898837897298',
    projectId: 'crud-e044a',
    storageBucket: 'crud-e044a.appspot.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9LV99QjdzNh5A2X_ZIHHrbhgJ-4fsnME',
    appId: '1:898837897298:ios:c9568833d9fe66a99b7f8b',
    messagingSenderId: '898837897298',
    projectId: 'crud-e044a',
    storageBucket: 'crud-e044a.appspot.com',
    iosBundleId: 'com.example.app2.RunnerTests',
  );
}
